name: generate demo files

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: compile
      run: | 
        yarn install
        yarn build
      
    - name: commit & push
      run: |
        if ! git diff --exit-code --quiet
        then
          git add -A
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update dist/index.js"
          git push
        fi